name: (CI) Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: npm run generate
      - run: npm exec -- prettier --check .
      - run: npm exec -- eslint .
      - run: npm exec -- tsc --noEmit
      - run: npm run test
