name: (CI) Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: "2025.3.11" # pin version, can't hurt
      - run: pnpm i
      - run: pnpm generate
      - run: pnpm exec -- prettier --check .
      - run: pnpm exec -- eslint .
      - run: pnpm exec -- tsc --noEmit
      - run: pnpm test
