name: ci

on:
  pull_request:
    branches: [ main ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i
      - run: pnpm generate

      # All the actual checks
      - run: pnpm run ci