name: Test
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Dependencies
      - uses: ./.github/actions/pnpm_install

      # Codegen
      - run: pnpm generate

      # Tests
      - run: pnpm lint:biome
      - run: pnpm lint:typescript
      - run: pnpm test
